### PR TITLE
[Automated PR] Bump KTLint and/or Google Java Formatter

### PR DESCRIPTION
**Pull request by macisamuele**
Bump KTLint and/or Google Java Formatter

*Auto-generated* by [bump-releases](https://github.com/macisamuele/language-formatters-pre-commit-hooks/actions/workflows/bump-releases.yaml)

### CODE REVIEW

**Comment by cortinico** [comment]
For some reason tests are failing on windows. Do you happen to know why @macisamuele ?

**Comment by macisamuele** [comment]
I'll be looking into the windows failures.
The bright side is that tests did got executed for the automated PR (so at least #62 worked)

**Comment by macisamuele** [comment]
@cortinico from a very superficial (possibly still incorrect) analysis I see that windows tests are failing because:
* ktlint requires relative paths, but it does look for paths with the forward-slash (`/`) and in windows the path separator is `\`.
  I have to check how in real pre-commit executions the path would be passed in to understand if this is testing issue or this would break during real execution as well
* even assuming that we can replace `\` with `/` ([here](https://gist.github.com/macisamuele/47c96b309d2eb0747bb3395a036878bd)), tests would continue to fail because *seems* that ktlint does not write the fixed file even if `--autofix` is passed in.

Considering the above findings, I'm going to look more into this hoping to identify what is the root cause of this and hoping that it is testing setup rather than a big regression in ktlint.

**Comment by macisamuele** [comment]
Manually rebased PR on top of #68 .
Please let's merge the 2 PRs separately.

**Review by cortinico — APPROVED** [review]

**Pull request merged**
