### PR TITLE
Update to ktlint 0.48.1

### PR DESCRIPTION
**Pull request by detouched**
Replace `--verbose` option with `--log-level debug`.

### CODE REVIEW

**Comment by macisamuele** [comment]
I'm not familiar with the difference between log-level and verbose, can you please provide context in why is the change helpful?

Moreover, can we avoid updating the ktlon version in here? There is already #138 doing it.

**Comment by detouched** [comment]
Sorry, my bad, didn't check for open PRs before raising this one.

The reason for this change is that `--verbose` is deprecated, in fact ktlint 0.48.1 returns an error when it is provided:
```
[cwd=/Users/detouched/Work/_devops/project] Run command: ('java', '--add-opens', 'java.base/java.lang=ALL-UNNAMED', '-jar', '/Users/detouched/.cache/pre-commit/ktlint0.48.1.jar', '--verbose', '--relative', '--', 'src/test/kotlin/integration/org/github/detouched/devops/controllers/StateControllerTest.kt')
[return_code=1] | 18:27:15.336 [main] ERROR com.pinterest.ktlint.internal.KtlintCommandLine - Options '--debug', '--trace', '--verbose' and '-v' are deprecated and replaced with option '--log-level=<level>' or '-l=<level>'.
```

**Comment by macisamuele** [comment]
I was not aware of it, due to unrelated test failures I was not focusing yet on the ktlint update.
Please make sure to rebase your changes on the latest version of the repository and to keep the ktlint version bump.
As soon as tests are going to be green I'll merge this PR and release the new version

**Comment by detouched** [comment]
Looks like I overlooked another `--verbose` argument. Let me fix that.

**Pull request merged**
