### PR TITLE
Add --indent and --trailing-commas arguments for toml

### LINKED ISSUE #152: Allow trailing comma in TOML
Could trailing commas for TOML be configurable? I'd rather keep them (in fact, enforce them). Trailing commas lead to better git diff.

### PR DESCRIPTION
**Pull request by maresb**
If there is interest in merging, let me know and I'll look into making tests.

Closes #152.

### CODE REVIEW

**Comment by macisamuele** [comment]
Thanks for working on this.
Please add test coverage and I'll be happy to merge it

**Comment by maresb** [comment]
Excellent, thanks!!! I'll write some tests.

**Comment by maresb** [comment]
@macisamuele, ready for review. Thanks!

**Comment by macisamuele** [comment]
Running tests on the pr now.
Later today or tomorrow, I'll fully review the changes even though I don't suspect any dramatic changes to be requested (if any).

Thanks a lot for contributing to the project.

**Comment by maresb** [comment]
Excellent, thanks! I'm looking forward to any feedback.

**Review by macisamuele — APPROVED** [review]
Changes looks overall good to me.
I'll be adding a few extra tests to ensure trailing commas functionalities.

Thanks a lot for your support.

**Pull request merged**
