### PR TITLE
Preserve comments in toml with tomlkit

### PR DESCRIPTION
**Pull request by Skylion007**
Should fix parts of #39 by switching the ml parser to tomlkit.

### CODE REVIEW

**Comment by Skylion007** [comment]
This PR should probably also include sub-table indenting from: https://github.com/macisamuele/language-formatters-pre-commit-hooks/issues/39#issuecomment-702962976

**Comment by Skylion007** [comment]
@CAM-Gerlach

**Comment by macisamuele** [comment]
@Skylion007 thanks for the PR and sorry for a such long radio silence.
By checking the code it seems a _copy&paste_ of the code provided by [`toml-sort`](https://pypi.org/project/toml-sort/) library ([code](https://github.com/pappasam/toml-sort/blob/31912b0723445b1c02aa471e84fcc55f07371055/toml_sort/tomlsort.py#L22-L142)).

Is there a reason to not use the library directly?

**Comment by Skylion007** [comment]
Lack of Python 2 support would be the main reason.

**Comment by CAM-Gerlach** [comment]
Sorry for the radio silence as well, was on a long trip and dealing with some personal and academic stuff.

> Lack of Python 2 support would be the main reason.

Its ultimately up to @macisamuele , but unless that's a design goal of this project for a particular reason, I'm not sure how that's a deal-breaker in 2021, with Py2 EoL for over a year now, and given that Pre-Commit automatically installs and manages the runtimes for its hooks, each fully isolated from one another, such that the Python version used/supported is effectively transparent to the hook's users? Or is there something I'm missing?

**Comment by macisamuele** [comment]
> Lack of Python 2 support would be the main reason.

Keeping Python2 support (if it does not add maintenance cost is fine) but importing/copying a whole library for that seems a bit too much.  Python2 is EoL by over a year so I would be more than happy to drop Python2 support and have toml-sort dependency used.

We will just make sure to release a major version afterword to ensure that Python support drop is well communicated

**Review by macisamuele — CHANGES_REQUESTED** [review]
Please add toml-sort as dependency in order to avoid this much code duplication.

If tests will fail on Python2, you can
  1) ignore them as we will need to properly drop Python2 support in a separate PR
  2) or we can update the github actions ([here](https://github.com/macisamuele/language-formatters-pre-commit-hooks/blob/de24fbdc7f1efa6b55e0ba3121e1f21890a87fa7/.github/workflows/build.yaml#L17)) by removing 2.7 from the list of tested python versions

Once this will be merged I'll make sure to follow-up and release a major release (due to the Python version support drop)

**Comment by Skylion007** [comment]
@macisamuele Reverted to vanilla toml sort.

**Review by macisamuele — APPROVED** [review]
@Skylion007 thanks a lot for taking care of this.

Tomorrow I'll be preparing the release (and making sure that Python2 is fully out of the repo)

**Pull request merged**
